templates [ci skip] Updating packages templates.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -7,12 +7,14 @@ workflows:
   version: 2
   test:
     jobs:
-    - test-310:
+    - test-310-src:
         context: << pipeline.parameters.context_name >>
-    - test-311:
+    - test-310-bin:
+        context: << pipeline.parameters.context_name >>
+    - test-311-src:
         context: << pipeline.parameters.context_name >>
 jobs:
-  test-310:
+  test-310-src:
     #    machine: true
     #    resource_class: zuper-ci-ns/my-resource-class
     environment:
@@ -23,7 +25,6 @@ jobs:
       DEPS_INSTALL_TIMEOUT: 10m
       COVER_PACKAGES: quickapp,quickapp_tests,reprep_quickapp
       TEST_PACKAGES: quickapp_tests
-      PIP_INDEX_URL: ${PIP_INDEX_URL_SRC}
       Z_SERVICE_LOG: zuper_loghandle.log
       Z_SERVICE_PROC: zuper_proc_local.proc
       Z_SERVICE_FS: zuper_fs_local.use_local_fs
@@ -47,6 +48,8 @@ jobs:
     - run:
         name: Install deps
         command: |
+          export PIP_INDEX_URL="${PIP_INDEX_URL_SRC}"
+          echo PIP_INDEX_URL="${PIP_INDEX_URL}"
           shyaml get-values install_requires < project.pp1.yaml > .requirements.txt
           python3 -m pip install -U pip
           timeout ${DEPS_INSTALL_TIMEOUT} python3 -m pip install  -r .requirements.txt
@@ -55,6 +58,8 @@ jobs:
     - run:
         name: Install testing deps
         command: |
+          export PIP_INDEX_URL="${PIP_INDEX_URL_SRC}"
+          echo PIP_INDEX_URL="${PIP_INDEX_URL}"
           shyaml get-values tests_require < project.pp1.yaml > .requirements_tests.txt
           timeout ${DEPS_INSTALL_TIMEOUT} python3 -m pip install  -r .requirements_tests.txt
           rm .requirements_tests.txt
@@ -62,6 +67,8 @@ jobs:
     - run:
         name: Python stats
         command: |
+          export PIP_INDEX_URL="${PIP_INDEX_URL_SRC}"
+          echo PIP_INDEX_URL="${PIP_INDEX_URL}"
           pipdeptree | tee  build-stats/pipdeptree.txt
           python3 -m pip  list   | sort | tee  build-stats/pip-list.txt
           python3 -m pip  freeze | sort | tee  build-stats/pip-freeze.txt
@@ -74,6 +81,8 @@ jobs:
     - run:
         name: setup.py develop
         command: |
+          export PIP_INDEX_URL="${PIP_INDEX_URL_SRC}"
+          echo PIP_INDEX_URL="${PIP_INDEX_URL}"
           python3 -m pip install -e . --prefix ~/.local --no-deps
 
     - run:
@@ -115,11 +124,15 @@ jobs:
 
     - run:
         name: Add more packages
-        command: python3 -m pip install zuper-fs-local-z7 zuper-proc-local-z7 zuper-notes-z7
-          zuper-loghandle-z7
+        command: |-
+          export PIP_INDEX_URL="${PIP_INDEX_URL_SRC}"
+          echo PIP_INDEX_URL="${PIP_INDEX_URL}"
+          python3 -m pip install zuper-fs-local-z7 zuper-proc-local-z7 zuper-notes-z7 zuper-loghandle-z7
     - run:
         name: quickapp_tests
         command: |
+          export PIP_INDEX_URL="${PIP_INDEX_URL_SRC}"
+          echo PIP_INDEX_URL="${PIP_INDEX_URL}"
           set -euxo pipefail
           TEST_MODULES=$(circleci tests split <.circleci/quickapp_tests.tests)
           echo "TEST_MODULES=[$TEST_MODULES]"
@@ -174,7 +187,7 @@ jobs:
           chmod +x codecov
           ./codecov  
     resource_class: small
-  test-311:
+  test-310-bin:
     #    machine: true
     #    resource_class: zuper-ci-ns/my-resource-class
     environment:
@@ -185,7 +198,179 @@ jobs:
       DEPS_INSTALL_TIMEOUT: 10m
       COVER_PACKAGES: quickapp,quickapp_tests,reprep_quickapp
       TEST_PACKAGES: quickapp_tests
-      PIP_INDEX_URL: ${PIP_INDEX_URL_SRC}
+      Z_SERVICE_LOG: zuper_loghandle.log
+      Z_SERVICE_PROC: zuper_proc_local.proc
+      Z_SERVICE_FS: zuper_fs_local.use_local_fs
+    docker:
+    - image: ${DOCKER_REGISTRY}/${DOCKER_TARGET_ORG}/${DOCKER_REPO_PREFIX}zuper-ci-3.10:${Z_DISTRO}
+      auth:
+        username: $DOCKER_USERNAME
+        password: $DOCKER_PASSWORD
+    working_directory: ~/repo
+    steps:
+    - checkout
+    - run:
+        name: Build statistics
+        command: |
+          mkdir -p build-stats
+          # env | sort | tee  build-stats/env.txt
+          env | sort
+    - store_artifacts:
+        path: build-stats
+        destination: build-stats
+    - run:
+        name: Install deps
+        command: |
+          export PIP_INDEX_URL="${PIP_INDEX_URL_BIN}"
+          echo PIP_INDEX_URL="${PIP_INDEX_URL}"
+          shyaml get-values install_requires < project.pp1.yaml > .requirements.txt
+          python3 -m pip install -U pip
+          timeout ${DEPS_INSTALL_TIMEOUT} python3 -m pip install  -r .requirements.txt
+          rm .requirements.txt
+
+    - run:
+        name: Install testing deps
+        command: |
+          export PIP_INDEX_URL="${PIP_INDEX_URL_BIN}"
+          echo PIP_INDEX_URL="${PIP_INDEX_URL}"
+          shyaml get-values tests_require < project.pp1.yaml > .requirements_tests.txt
+          timeout ${DEPS_INSTALL_TIMEOUT} python3 -m pip install  -r .requirements_tests.txt
+          rm .requirements_tests.txt
+
+    - run:
+        name: Python stats
+        command: |
+          export PIP_INDEX_URL="${PIP_INDEX_URL_BIN}"
+          echo PIP_INDEX_URL="${PIP_INDEX_URL}"
+          pipdeptree | tee  build-stats/pipdeptree.txt
+          python3 -m pip  list   | sort | tee  build-stats/pip-list.txt
+          python3 -m pip  freeze | sort | tee  build-stats/pip-freeze.txt
+          python3 -m pip cache list | tee  build-stats/pip-cache.txt
+
+    - store_artifacts:
+        path: build-stats
+        destination: build-stats
+
+    - run:
+        name: setup.py develop
+        command: |
+          export PIP_INDEX_URL="${PIP_INDEX_URL_BIN}"
+          echo PIP_INDEX_URL="${PIP_INDEX_URL}"
+          python3 -m pip install -e . --prefix ~/.local --no-deps
+
+    - run:
+        name: Make docs
+        command: |
+          FILE=src/conf.py
+          mkdir -p out/docs
+          if test -f "$FILE"; then
+              sphinx-build src out/docs
+          fi
+
+    - store_artifacts:
+        path: out/docs
+        destination: docs
+    - run:
+        background: true
+        name: services
+        command: |
+          TARGET=services
+          if make -n $TARGET ; then
+              make $TARGET
+          else
+              echo "Target $TARGET not defined"
+          fi
+    - run:
+        name: pre-circle-tests
+        command: |
+          TARGET=pre-circle-tests
+          if make -n $TARGET ; then
+              make $TARGET
+          else
+              echo "Target $TARGET not defined"
+          fi
+    # - run:
+    #     name: Notebooks
+    #     command: |
+    #       make -C notebooks cleanup all
+
+
+    - run:
+        name: Add more packages
+        command: |-
+          export PIP_INDEX_URL="${PIP_INDEX_URL_BIN}"
+          echo PIP_INDEX_URL="${PIP_INDEX_URL}"
+          python3 -m pip install zuper-fs-local-z7 zuper-proc-local-z7 zuper-notes-z7 zuper-loghandle-z7
+    - run:
+        name: quickapp_tests
+        command: |
+          export PIP_INDEX_URL="${PIP_INDEX_URL_BIN}"
+          echo PIP_INDEX_URL="${PIP_INDEX_URL}"
+          set -euxo pipefail
+          TEST_MODULES=$(circleci tests split <.circleci/quickapp_tests.tests)
+          echo "TEST_MODULES=[$TEST_MODULES]"
+          if [ -z "$TEST_MODULES" ]; then
+            echo "\$TEST_MODULES is empty"
+            exit 0
+          else
+            echo "\$TEST_MODULES is NOT empty"
+          fi
+          mkdir -p out/test-results
+          xunit_output=$PWD/out/test-results/nose-${CIRCLE_NODE_INDEX}-quickapp_tests-xunit.xml
+          timeout 30m nose2 --with-coverage \
+              --plugin nose2.plugins.junitxml \
+              --junit-xml \
+              --junit-xml-path ${xunit_output} \
+              $TEST_MODULES
+          # TODO: cover packages
+    - run:
+        name: post-circle-tests
+        command: |
+          TARGET=post-circle-tests
+          if make -n $TARGET ; then
+              make $TARGET
+          else
+              echo "Target $TARGET not defined"
+          fi
+
+    - store_test_results:
+        path: out/test-results
+
+    - run:
+        name: Coverage report
+        when: always
+        command: |
+          coverage combine || true
+          coverage html -d out/coverage/${CIRCLE_NODE_INDEX} || true
+          coverage xml || true
+
+    - store_artifacts:
+        path: out/coverage
+        destination: coverage
+
+    - store_artifacts:
+        path: out/tests
+        destination: tests
+
+    - run:
+        name: CodeCov
+        when: always
+        command: |
+          curl -Os https://uploader.codecov.io/latest/linux/codecov
+          chmod +x codecov
+          ./codecov  
+    resource_class: small
+  test-311-src:
+    #    machine: true
+    #    resource_class: zuper-ci-ns/my-resource-class
+    environment:
+      COLUMNS: '160'
+      # default is /usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+      PATH: /root/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+      CONTEXT_NAME: << pipeline.parameters.context_name >>
+      DEPS_INSTALL_TIMEOUT: 10m
+      COVER_PACKAGES: quickapp,quickapp_tests,reprep_quickapp
+      TEST_PACKAGES: quickapp_tests
       Z_SERVICE_LOG: zuper_loghandle.log
       Z_SERVICE_PROC: zuper_proc_local.proc
       Z_SERVICE_FS: zuper_fs_local.use_local_fs
@@ -209,6 +394,8 @@ jobs:
     - run:
         name: Install deps
         command: |
+          export PIP_INDEX_URL="${PIP_INDEX_URL_SRC}"
+          echo PIP_INDEX_URL="${PIP_INDEX_URL}"
           shyaml get-values install_requires < project.pp1.yaml > .requirements.txt
           python3 -m pip install -U pip
           timeout ${DEPS_INSTALL_TIMEOUT} python3 -m pip install  -r .requirements.txt
@@ -217,6 +404,8 @@ jobs:
     - run:
         name: Install testing deps
         command: |
+          export PIP_INDEX_URL="${PIP_INDEX_URL_SRC}"
+          echo PIP_INDEX_URL="${PIP_INDEX_URL}"
           shyaml get-values tests_require < project.pp1.yaml > .requirements_tests.txt
           timeout ${DEPS_INSTALL_TIMEOUT} python3 -m pip install  -r .requirements_tests.txt
           rm .requirements_tests.txt
@@ -224,6 +413,8 @@ jobs:
     - run:
         name: Python stats
         command: |
+          export PIP_INDEX_URL="${PIP_INDEX_URL_SRC}"
+          echo PIP_INDEX_URL="${PIP_INDEX_URL}"
           pipdeptree | tee  build-stats/pipdeptree.txt
           python3 -m pip  list   | sort | tee  build-stats/pip-list.txt
           python3 -m pip  freeze | sort | tee  build-stats/pip-freeze.txt
@@ -236,6 +427,8 @@ jobs:
     - run:
         name: setup.py develop
         command: |
+          export PIP_INDEX_URL="${PIP_INDEX_URL_SRC}"
+          echo PIP_INDEX_URL="${PIP_INDEX_URL}"
           python3 -m pip install -e . --prefix ~/.local --no-deps
 
     - run:
@@ -277,11 +470,15 @@ jobs:
 
     - run:
         name: Add more packages
-        command: python3 -m pip install zuper-fs-local-z7 zuper-proc-local-z7 zuper-notes-z7
-          zuper-loghandle-z7
+        command: |-
+          export PIP_INDEX_URL="${PIP_INDEX_URL_SRC}"
+          echo PIP_INDEX_URL="${PIP_INDEX_URL}"
+          python3 -m pip install zuper-fs-local-z7 zuper-proc-local-z7 zuper-notes-z7 zuper-loghandle-z7
     - run:
         name: quickapp_tests
         command: |
+          export PIP_INDEX_URL="${PIP_INDEX_URL_SRC}"
+          echo PIP_INDEX_URL="${PIP_INDEX_URL}"
           set -euxo pipefail
           TEST_MODULES=$(circleci tests split <.circleci/quickapp_tests.tests)
           echo "TEST_MODULES=[$TEST_MODULES]"
@@ -337,4 +534,4 @@ jobs:
           ./codecov  
     resource_class: small
 
-# sigil ff87e9fae8c201163aba3c000b3a00e1
+# sigil 2875ad1246d457bee25f62fea258ad56
